### ISSUE TITLE
Implement MySQL connector

### ISSUE THREAD

**Issue by Ullaakut** [Wikia/sroka#22]
Part of #20 

Implementing a connector for MySQL databases seems like a great idea, since it is one of the most widely used relational databases.

## Implementation Proposition

Using the [`mysql.connector`](https://dev.mysql.com/doc/connectors/en/connector-python.html) package is a safe bet, since it is the official package supported by MySQL.

**Comment by martynaut** [comment]
Thank you @Ullaakut :) We will take a look at PR this week.

**Comment by martynaut** [comment]
MySQL connector was merged in dev branch. Will be released in the next release. Closing.
